spring.application.name=hospital-admin-service
server.port=8082

# PostgreSQL Database Configuration
# spring.datasource.url=jdbc:postgresql://localhost:5432/PSIMS_MANAGEMENT
# spring.datasource.username=postgres
# spring.datasource.password=Psims@21137
spring.datasource.url=jdbc:postgresql://psitmedical.postgres.database.azure.com:5432/Adminstartion?sslmode=require&preferQueryMode=simple&connectTimeout=30
spring.datasource.username=psitmedical
spring.datasource.password=bbms@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection Pool Settings (Optional but helpful for timeouts)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
#expiry after 24hrs
jwt.expiration=86400000 

# Hide Hibernate SQL logs
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.type.descriptor.sql=OFF

# Disable Hibernate internal logs
logging.level.org.hibernate=ERROR
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.springframework.orm.jpa=ERROR
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.springframework=ERROR

springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.operationsSorter=alpha
